# Generated by Django 5.0.3 on 2024-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_enterproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, 'No  faol'), (2, "Yo'lda"), (3, 'Qaytarilgan'), (4, 'Qabul qilingan')], default=1),
            preserve_default=False,
        ),
    ]
