# Generated by Django 5.0.3 on 2024-04-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
    ]
