# Generated by Django 5.0.3 on 2024-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode_img',
            field=models.ImageField(blank=True, upload_to='qrcode-img/'),
        ),
    ]
